# -*- coding: utf-8 -*-
"""mytranspose.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1quk30_sH9XJgJh8sEcoVFbj3eGsYJ_6V
"""

import numpy as np
import pandas as pd
import math

def mytranspose(x):
    # Check if the input is a data frame
    if isinstance(x, pd.DataFrame):
        # Convert the data frame to a matrix
        x = x.to_numpy()
        y = np.ones((x.shape[1], x.shape[0]))
        y = y.astype('unicode')
        for i in range(x.shape[0]):
          for j in range(x.shape[1]):
            y[j, i] = x[i, j]

        return y

    # Check if the input is a vector
    if isinstance(x, np.ndarray) and x.ndim == 1:
        return np.array([list(x)])

    # Check if the input matrix is empty
    if x is None:
        return x

    # Create a matrix y with the dimensions of x transposed
    y = np.ones((x.shape[1], x.shape[0]))

    # Loop through each row i and column j of x
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
          y[j, i] = x[i, j]

    return y

