# -*- coding: utf-8 -*-
"""testmytransposeipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hTO_I-uZtqelw7aR8mI56T1RshEtkSfr
"""

myvar1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
expected1 = myvar1.transpose()
(expected1 == mytranspose(myvar1)).all()

#np.array() with no parameters occurs error
myvar1 = None
expected2 = None
expected2 == mytranspose(myvar1)

myvar1 = np.array([1, 2])
expected3 = myvar1.transpose()
(expected3 == mytranspose(myvar1)).all()

myvar1 = np.array([[1], [2]])
expected4 = myvar1.transpose()
(expected4 == mytranspose(myvar1)).all()

myvar2 = np.array([1, 2, None, 3])
expected5 = np.array([[1, 2, None, 3]])
(expected5 == mytranspose(myvar2)).all()

myvar2 = np.array([None])
expected6 = np.array([[None]])
(expected6 == mytranspose(myvar2)).all()

#np.array() occurs error
myvar2 = None
expected7 = None
expected7 == mytranspose(myvar2)

mydata3 = pd.DataFrame({'d': [1, 2, 3, 4], 'e': ["red", "white", "red", None], 'f': [True,True,True,False]})
expected8 = np.array([['1', '2', '3', '4'],
       ['red', 'white', 'red', 'None'],
       ['True', 'True', 'True', 'False']])
(expected8 == mytranspose(mydata3)).all()