# -*- coding: utf-8 -*-
"""V1_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dMns-vHAAu9yf0iHmp4dpivs8BKv0grP
"""

myvar1 = np.array([[1, 3, 5, 7], [9, 10, 11, 13]])
myvar1.transpose()
expected1 = myvar1.transpose()
(expected1 == mytranspose(myvar1)).all()

mydata4 = pd.DataFrame({'country': ['korea', 'japan', 'usa'], 'population': [3, 2, 1]})
expected4 = np.array([['korea', 'japan', 'usa'],
       [3, 2, 1]])
(expected4 == mytranspose(mydata4)).all()

